name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Install dependencies
        run: node runner-electron.js

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}

  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Install dependencies
        run: node runner-chrome.js

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
    env:
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}

  cypress-firefox-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.2

      - name: Install dependencies
        run: node runner-firefox.js

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
    env:
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
